
# Project information

site_name: GoogleTI ハンズオンセミナー
site_short_name: GoogleTI ハンズオン
site_description: 'このハンズオンセミナーは Google Threat Intelligence を利用して、脅威インテリジェンスに関連する様々な活用方法を体験します'
# site_author: ''
# site_url: ''
# copyright: ''


# Configuration
theme: 
  # name: readthedocs
  name: material
  language: ja
  font: 
    text: Noto Sans JP
    code: JetBrains Mono

  # feature:
  #   tabs: true
  # favicon: ico/ki.png


# Extensions
markdown_extensions:
  - admonition
  # - pymdownx.details

# Navigation
nav:
  - 概要: 'index.md'
  - 'ASM / DTM 機能': 
    - '1.1. ASMへのアクセス': '01-environment-access.md'
  - 'MATI / VT 機能': 
    - '1.1. VTへのアクセス': '01-environment-access.md'



#  - '1. ASMへのアクセス': '01-environment-access.md'
#  - '2. 設定の確認': '02-configuration-check.md'
#  - '3. 探索結果の確認': 
#    - '3.1. DashBoardの確認': '031-check-dashboard.md'
#    - '3.2. Entitiesの確認1': '032-check-entities1.md'
#    - '3.3. Entitiesの確認2': '033-check-entities2.md'
#    - '3.4. Technologiesの確認': '033-check-technologies.md'
#    - '3.5. Issuesの確認': '034-check-issues.md'
#    - '3.6. Insightsの確認': '035-check-insights.md'
#  - '4. 自組織の状況確認': '04-check-ownproject.md'
#  - '5. 応用編': 
#    - '5.1. Export機能': '051-adv-export.md'
#    - '5.2. 運用機能': '052-adv-operation.md'
#    - '5.3. Library': '053-adv-library.md'
#    - '5.4. 自由時間': '054-adv-break.md'
  - '6. まとめ': '06-summary.md'


